app = "lodash-as-a-service"
primary_region = "cdg"

[http_service]
internal_port = 3000        # The exposed port
auto_stop_machines = 'stop' # Stop (not suspend) machines when idle
min_machines_running = 0    # Stop all machines (default is keep one up)
auto_start_machines = true
force_https = true

# Healthcheck
[[http_service.checks]]
path = '/health'
method = 'GET'
grace_period = '30s' # Wait that long before the first test
interval = '1m'      # Check every...
timeout = '10s'      # Considered dead if no response in...

[[vm]]
size = "shared-cpu-1x"
memory = "256mb"
