// Configuration for the Lodash transformation API

// Special constant for generator methods (when using _ as input)
export const LODASH_ROOT = Symbol("lodash-root");

// Whitelist of allowed Lodash methods
export const ALLOWED_METHODS = [
  // String methods
  "camelCase",
  "capitalize",
  "deburr",
  "endsWith",
  "escape",
  "escapeRegExp",
  "kebabCase",
  "lowerCase",
  "lowerFirst",
  "pad",
  "padEnd",
  "padStart",
  "parseInt",
  "repeat",
  "removeEmojis",
  "replaceAll",
  "replace",
  "slice",
  "snakeCase",
  "split",
  "startCase",
  "startsWith",
  "toLower",
  "toUpper",
  "toLowerCase",
  "toUpperCase",
  "trim",
  "trimEnd",
  "trimStart",
  "truncate",
  "unescape",
  "upperCase",
  "upperFirst",
  "words",

  // Array methods
  "compact",
  "concat",
  "difference",
  "drop",
  "dropRight",
  "flatten",
  "flattenDeep",
  "head",
  "initial",
  "intersection",
  "join",
  "last",
  "reverse",
  "shuffle",
  "sort",
  "sortNumeric",
  "slice",
  "tail",
  "take",
  "takeRight",
  "union",
  "uniq",
  "uniqBy",
  "without",

  // Utility methods
  "identity",
  "noop",
  "range",
  "stubArray",
  "stubFalse",
  "stubObject",
  "stubString",
  "stubTrue",
  "times",
  "toPath",
  "uniqueId",
];