// Configuration for the Lodash transformation API

// Special constant for generator methods (when using _ as input)
export const LODASH_ROOT = Symbol("lodash-root");

// Methods that accept transformation chains as arrays
export const CHAIN_METHODS = [
  "map",
  "filter",
  // Add other methods here as needed (reduce, etc.)
];

// Whitelist of allowed Lodash methods
export const ALLOWED_METHODS = [
  // String methods
  "camelCase",
  "capitalize",
  "deburr",
  "endsWith",
  "escape",
  "escapeRegExp",
  "kebabCase",
  "lowerCase",
  "lowerFirst",
  "pad",
  "padEnd",
  "padStart",
  "parseInt",
  "repeat",
  "removeEmojis",
  "replaceAll",
  "replace",
  "slice",
  "snakeCase",
  "split",
  "startCase",
  "startsWith",
  "toLower",
  "toUpper",
  "toLowerCase",
  "toUpperCase",
  "trim",
  "trimEnd",
  "trimStart",
  "truncate",
  "unescape",
  "upperCase",
  "upperFirst",
  "words",

  // Array methods
  "compact",
  "concat",
  "difference",
  "drop",
  "dropRight",
  "filter",
  "find",
  "flatMap",
  "flatten",
  "flattenDeep",
  "head",
  "initial",
  "intersection",
  "join",
  "last",
  "map",
  "reverse",
  "shuffle",
  "sort",
  "sortNumeric",
  "slice",
  "tail",
  "take",
  "takeRight",
  "union",
  "uniq",
  "uniqBy",
  "without",

  // Utility methods
  "get",
  "identity",
  "noop",
  "range",
  "renameKey",
  "stubArray",
  "stubFalse",
  "stubObject",
  "stubString",
  "stubTrue",
  "times",
  "toPath",
  "uniqueId",
];
